#[test_only]
/// kido_nautilus::decision against decisions signed by Kido's TypeScript enclave signer
/// (tests/vectors.move, generated by packages/privacy/scripts/nautilus-vectors.ts).
module kido_nautilus::decision_tests;

use enclave::enclave::{Self, Cap, Enclave, EnclaveConfig};
use kido_nautilus::decision::{Self, DECISION, Registry};
use kido_nautilus::vectors as v;
use sui::clock::{Self, Clock};
use sui::test_scenario::{Self as ts, Scenario};

const OWNER: address = @0xA11CE;

fun setup(now_ms: u64): (Scenario, Clock, Registry, EnclaveConfig<DECISION>, Enclave<DECISION>) {
    let mut s = ts::begin(OWNER);
    decision::init_for_testing(s.ctx());
    s.next_tx(OWNER);
    let mut clock = clock::create_for_testing(s.ctx());
    clock.set_for_testing(now_ms);
    let reg = s.take_shared<Registry>();
    let config = s.take_shared<EnclaveConfig<DECISION>>();
    let e = enclave::new_enclave_for_testing<DECISION>(v::enclave_pk(), s.ctx());
    (s, clock, reg, config, e)
}

fun finish(s: Scenario, clock: Clock, reg: Registry, config: EnclaveConfig<DECISION>, e: Enclave<DECISION>) {
    ts::return_shared(reg);
    ts::return_shared(config);
    enclave::destroy(e);
    clock.destroy_for_testing();
    s.end();
}

fun accept(reg: &mut Registry, config: &EnclaveConfig<DECISION>, e: &Enclave<DECISION>, d: v::Signed, clock: &Clock): bool {
    let (key, act, bp, t, sig) = v::fields(&d);
    decision::accept(reg, config, e, key, act, bp, t, sig, clock)
}

#[test]
fun signed_decision_accepted() {
    let (s, clock, mut reg, config, e) = setup(v::t0_ms() + 1_000);
    assert!(accept(&mut reg, &config, &e, v::act_at_t0(), &clock));
    finish(s, clock, reg, config, e);
}

#[test]
fun newer_decision_for_the_same_key_accepted() {
    let (s, mut clock, mut reg, config, e) = setup(v::t0_ms() + 1_000);
    assert!(accept(&mut reg, &config, &e, v::act_at_t0(), &clock));
    clock.set_for_testing(v::t0_ms() + 61_000);
    assert!(!accept(&mut reg, &config, &e, v::hold_at_t1(), &clock));
    finish(s, clock, reg, config, e);
}

#[test, expected_failure(abort_code = decision::EReplay)]
fun replayed_decision_rejected() {
    let (s, clock, mut reg, config, e) = setup(v::t0_ms() + 1_000);
    accept(&mut reg, &config, &e, v::act_at_t0(), &clock);
    accept(&mut reg, &config, &e, v::act_at_t0(), &clock);
    finish(s, clock, reg, config, e);
}

#[test, expected_failure(abort_code = decision::EReplay)]
fun older_decision_after_a_newer_one_rejected() {
    let (s, mut clock, mut reg, config, e) = setup(v::t0_ms() + 61_000);
    accept(&mut reg, &config, &e, v::hold_at_t1(), &clock);
    clock.set_for_testing(v::t0_ms() + 62_000);
    accept(&mut reg, &config, &e, v::act_at_t0(), &clock);
    finish(s, clock, reg, config, e);
}

#[test, expected_failure(abort_code = decision::EStale)]
fun stale_decision_rejected() {
    let (s, clock, mut reg, config, e) = setup(v::t0_ms() + 300_001);
    accept(&mut reg, &config, &e, v::act_at_t0(), &clock);
    finish(s, clock, reg, config, e);
}

#[test, expected_failure(abort_code = decision::EFromTheFuture)]
fun decision_from_the_future_rejected() {
    let (s, clock, mut reg, config, e) = setup(v::t0_ms() - 1);
    accept(&mut reg, &config, &e, v::act_at_t0(), &clock);
    finish(s, clock, reg, config, e);
}

#[test, expected_failure(abort_code = decision::EBadSignature)]
fun flipped_decision_rejected() {
    let (s, clock, mut reg, config, e) = setup(v::t0_ms() + 1_000);
    let (key, _act, bp, t, sig) = v::fields(&v::act_at_t0());
    decision::accept(&mut reg, &config, &e, key, false, bp, t, sig, &clock);
    finish(s, clock, reg, config, e);
}

#[test, expected_failure(abort_code = decision::EBadSignature)]
fun decision_bound_to_another_blueprint_rejected() {
    let (s, clock, mut reg, config, e) = setup(v::t0_ms() + 1_000);
    let (key, act, _bp, t, sig) = v::fields(&v::act_at_t0());
    decision::accept(&mut reg, &config, &e, key, act, x"00", t, sig, &clock);
    finish(s, clock, reg, config, e);
}

#[test, expected_failure(abort_code = decision::EBadSignature)]
fun decision_signed_by_an_unregistered_key_rejected() {
    let (s, clock, mut reg, config, e) = setup(v::t0_ms() + 1_000);
    accept(&mut reg, &config, &e, v::act_at_t0_other_key(), &clock);
    finish(s, clock, reg, config, e);
}

#[test, expected_failure(abort_code = decision::EWrongConfigVersion)]
fun enclave_from_a_superseded_configuration_rejected() {
    let (mut s, clock, mut reg, mut config, e) = setup(v::t0_ms() + 1_000);
    let cap = s.take_from_sender<Cap<DECISION>>();
    enclave::update_pcrs(&mut config, &cap, x"01", x"02", x"03");
    s.return_to_sender(cap);
    accept(&mut reg, &config, &e, v::act_at_t0(), &clock);
    finish(s, clock, reg, config, e);
}
