// Generated by packages/privacy/scripts/nautilus-vectors.ts. Do not edit.
#[test_only]
module kido_nautilus::vectors;

public struct Signed has copy, drop { decision_key: vector<u8>, act: bool, blueprint_hash: vector<u8>, timestamp_ms: u64, signature: vector<u8> }

public fun fields(s: &Signed): (vector<u8>, bool, vector<u8>, u64, vector<u8>) { (s.decision_key, s.act, s.blueprint_hash, s.timestamp_ms, s.signature) }
public fun t0_ms(): u64 { 1800000000000 }
public fun enclave_pk(): vector<u8> { x"197f6b23e16c8532c6abc838facd5ea789be0c76b2920334039bfa8b3d368d61" }

public fun act_at_t0(): Signed { Signed { decision_key: x"56d76b66092c721e42574e68a493b0b6a115425f135d874dd36a0ae881552b83", act: true, blueprint_hash: x"b2596f7f0ab80175348b9280fde5fc309cd8015fb2da260867a420e0166ab704", timestamp_ms: 1800000000000, signature: x"cf9f4c35357924f5471ec17c6f094d4589ba5551b0aca8009317cd4d99438a7eb1a1fee7e2c6bdcdac73d36e2a22e9859509adfc9350965035f941ca2d3f6c00" } }
public fun hold_at_t1(): Signed { Signed { decision_key: x"56d76b66092c721e42574e68a493b0b6a115425f135d874dd36a0ae881552b83", act: false, blueprint_hash: x"b2596f7f0ab80175348b9280fde5fc309cd8015fb2da260867a420e0166ab704", timestamp_ms: 1800000060000, signature: x"2254f8ca780e3934c53bc5a8f01371098bee35ec1460a070f59e6d5aece1e0fa6f8e81e02db7137bed1ae624eb0324835266ebbf1a827fa32575d5d05b38e703" } }
public fun act_at_t0_other_key(): Signed { Signed { decision_key: x"56d76b66092c721e42574e68a493b0b6a115425f135d874dd36a0ae881552b83", act: true, blueprint_hash: x"b2596f7f0ab80175348b9280fde5fc309cd8015fb2da260867a420e0166ab704", timestamp_ms: 1800000000000, signature: x"20992201b1f5f637f854a1e8f9b3186661468f4ef9c1d0c5e0799c2c569517688cd05806eacfebc3848dd65a4edb2c36fa69c616194d3b3a8c53d1b9a9cff503" } }
