/**
 * Generates the cross-language golden vectors.
 *
 * Run once (and re-run only on a deliberate schema change). The output is committed and BOTH
 * implementations must reproduce it:
 *   - TypeScript: packages/protocol/test/vectors.test.ts
 *   - Solidity:   contracts/test/GoldenVectors.t.sol  (reads this exact JSON via vm.readFile)
 *
 * The Solidity side does not call TypeScript and the TypeScript side does not call Solidity.
 * Both recompute from the schema, so agreement is evidence of a shared canonicalization rather
 * than of one implementation echoing the other.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { keccak256, toHex, type Address, type Hex } from "viem";
import {
  type Capability,
  capabilityDigest,
  domainSeparator,
  hashStruct,
  requestHash,
  CAPABILITY_TYPEHASH,
  REQUEST_TYPEHASH,
  CAPABILITY_TYPE_STRING,
  REQUEST_TYPE_STRING,
} from "../src/capability.js";

const EXECUTOR = "0x1111111111111111111111111111111111111111" as Address;
const AGENT = "0x2222222222222222222222222222222222222222" as Address;
const TARGET = "0x3333333333333333333333333333333333333333" as Address;

const base: Capability = {
  version: 1,
  agentIdentityHash: keccak256(toHex("treasury.agents.contextlock.eth#1")),
  agent: AGENT,
  chainId: 11155111n,
  executor: EXECUTOR,
  target: TARGET,
  value: 0n,
  calldataHash: keccak256(toHex("mock-calldata")),
  intentHash: keccak256(toHex("REBALANCE_SWAP:500")),
  policyHash: keccak256(toHex("policy-v1")),
  authorizationId: keccak256(toHex("auth-1")),
  contextCommitment: keccak256(toHex("ctx-v1")),
  issuedAt: 1800000000n,
  expiresAt: 1800000300n,
  nonce: 1n,
};

/** One mutation per security-relevant field: every one must move the digest. */
const mutations: Array<{ name: string; cap: Capability }> = [
  { name: "baseline", cap: base },
  { name: "version", cap: { ...base, version: 2 } },
  { name: "agentIdentityHash", cap: { ...base, agentIdentityHash: keccak256(toHex("other-identity")) } },
  { name: "agent", cap: { ...base, agent: "0x4444444444444444444444444444444444444444" as Address } },
  { name: "chainId", cap: { ...base, chainId: 1n } },
  { name: "executor", cap: { ...base, executor: "0x5555555555555555555555555555555555555555" as Address } },
  { name: "target", cap: { ...base, target: "0x6666666666666666666666666666666666666666" as Address } },
  { name: "value", cap: { ...base, value: 1n } },
  { name: "calldataHash", cap: { ...base, calldataHash: keccak256(toHex("attacker-calldata")) } },
  { name: "intentHash", cap: { ...base, intentHash: keccak256(toHex("other-intent")) } },
  { name: "policyHash", cap: { ...base, policyHash: keccak256(toHex("policy-v2")) } },
  { name: "authorizationId", cap: { ...base, authorizationId: keccak256(toHex("auth-2")) } },
  { name: "contextCommitment", cap: { ...base, contextCommitment: keccak256(toHex("ctx-v2")) } },
  { name: "issuedAt", cap: { ...base, issuedAt: 1800000001n } },
  { name: "expiresAt", cap: { ...base, expiresAt: 1800000301n } },
  { name: "nonce", cap: { ...base, nonce: 2n } },
];

const s = (c: Capability) => ({
  version: c.version,
  agentIdentityHash: c.agentIdentityHash,
  agent: c.agent,
  chainId: c.chainId.toString(),
  executor: c.executor,
  target: c.target,
  value: c.value.toString(),
  calldataHash: c.calldataHash,
  intentHash: c.intentHash,
  policyHash: c.policyHash,
  authorizationId: c.authorizationId,
  contextCommitment: c.contextCommitment,
  issuedAt: c.issuedAt.toString(),
  expiresAt: c.expiresAt.toString(),
  nonce: c.nonce.toString(),
});

const vectors = mutations.map(({ name, cap }) => ({
  name,
  capability: s(cap),
  structHash: hashStruct(cap),
  domainSeparator: domainSeparator(cap.chainId, cap.executor),
  digest: capabilityDigest(cap),
  requestHash: requestHash(cap),
}));

// Every mutation must produce a distinct digest, or the schema fails to bind that field.
const digests = new Set(vectors.map((v) => v.digest));
if (digests.size !== vectors.length) {
  throw new Error(
    `Digest collision: ${vectors.length} vectors produced only ${digests.size} distinct digests. ` +
      `A security-relevant field is not bound by the schema.`,
  );
}

const out = {
  _comment:
    "Golden EIP-712 vectors for the ContextLock capability schema. Generated by " +
    "packages/protocol/scripts/generate-vectors.ts. TypeScript and Solidity each recompute " +
    "these independently; neither reads the other. Regenerate ONLY on a deliberate schema change.",
  schemaVersion: 1,
  capabilityTypeString: CAPABILITY_TYPE_STRING,
  requestTypeString: REQUEST_TYPE_STRING,
  capabilityTypehash: CAPABILITY_TYPEHASH as Hex,
  requestTypehash: REQUEST_TYPEHASH as Hex,
  vectors,
};

const here = dirname(fileURLToPath(import.meta.url));
const path = join(here, "..", "test-vectors", "capability-vectors.json");
writeFileSync(path, JSON.stringify(out, null, 2) + "\n");
console.log(`wrote ${vectors.length} vectors -> ${path}`);
console.log(`capabilityTypehash = ${CAPABILITY_TYPEHASH}`);
console.log(`requestTypehash    = ${REQUEST_TYPEHASH}`);
console.log(`baseline digest    = ${vectors[0]!.digest}`);
