import type { ProviderManifest, TrustProfile } from "../types.js";

const R = "2026-09-26";
const trust = (providerId: string, t: Omit<TrustProfile, "providerId">): TrustProfile => ({ providerId, ...t });

/**
 * Seed provider manifests. Facts marked VERIFIED_* were checked by TRACE against live testnets or
 * official documentation (`.gauntlet/research/`); UNVERIFIED entries may be selected for planning
 * and simulation but never counted as live capability.
 */
export const PROVIDERS: ProviderManifest[] = [
  {
    schemaVersion: "kido.provider/v1",
    providerId: "ens",
    displayName: "ENS (Ethereum Name Service)",
    kind: "identity",
    category: "nameservice",
    chains: ["ethereum-sepolia"],
    capabilities: ["RESOLVE", "REVERSE_RESOLVE", "REGISTER", "SUBNAME", "TEXT_RECORDS", "ADDRESS_RECORD", "SCOPED_RECORD_MANAGER", "REVOKE", "EXPIRY"],
    version: "ensv2-beta (Sepolia)",
    sdk: [],
    deployments: {
      "ethereum-sepolia": {
        rootRegistry: "0x9703dbd26dab89504490994138cf2c575251a9ce",
        ethRegistry: "0x657ea849311d3d5823348dded7c2aaafb3ede09e",
        ethRegistrar: "0xabe76f6c8dfced81aa5a2bb8034202a7136b94ca",
        universalResolver: "0xeEeEEEeE14D718C2B47D9923Deab1335E144EeEe",
        legacyRegistry: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
        legacyPublicResolver: "0xE99638b40E4Fff0129D56f03b55b6bbC4BBE49b5",
        legacyNameWrapper: "0x0635513f179D50A207757E05759CbD106d7dFcE8",
      },
    },
    trust: trust("ens", {
      protects: ["human-readable binding of a name to records chosen by the name's controller"],
      verifies: ["record values are what the resolver returns for the current name owner/manager"],
      requiresTrustIn: ["name owner and delegated record managers", "resolver contract", "Ethereum consensus", "the RPC used to read it"],
      doesNotProtectAgainst: ["a compromised name owner rewriting records", "stale off-chain caches", "financial misuse — ENS grants no financial authority"],
      version: "ensv2-beta",
      sourceRefs: ["https://docs.ens.domains/ensv2/overview/", "https://docs.ens.domains/ensip/26/"],
    }),
    failureModes: ["resolver not found", "name expired", "ENSv2 interfaces change during beta"],
    limitations: ["ENSv2 is beta on Sepolia; ENSIP-25/26 are draft standards"],
    sources: [{ url: "https://docs.ens.domains/ensv2/overview/", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "contract code verified on Sepolia; registration flow pending live test",
    knowledgePack: "identity/ens",
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "suins",
    displayName: "SuiNS",
    kind: "identity",
    category: "nameservice",
    chains: ["sui-testnet"],
    capabilities: ["RESOLVE", "REVERSE_RESOLVE", "REGISTER", "SUBNAME", "ADDRESS_RECORD", "EXPIRY"],
    version: "unpinned",
    sdk: [],
    deployments: {},
    trust: trust("suins", {
      protects: ["human-readable binding of a Sui name to a target address and records"],
      verifies: ["current target/records of the name object"],
      requiresTrustIn: ["name NFT holder", "SuiNS packages and their upgrade authority", "Sui consensus"],
      doesNotProtectAgainst: ["compromised name holder", "financial misuse — SuiNS grants no financial authority"],
      version: "unpinned",
      sourceRefs: ["https://docs.suins.io/"],
    }),
    failureModes: ["name expired", "target unset"],
    limitations: ["capability set pending TRACE verification"],
    sources: [{ url: "https://docs.suins.io/", retrieved: R }],
    status: "UNVERIFIED",
    statusNote: "awaiting TRACE verification of testnet package ids and SDK",
    knowledgePack: "identity/suins",
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "kido-secret-store",
    displayName: "Kido host secret store",
    kind: "privacy",
    category: "secrets",
    chains: ["ethereum-sepolia", "sui-testnet"],
    capabilities: ["SECRET_STORAGE"],
    version: "1",
    sdk: [],
    deployments: {},
    trust: trust("kido-secret-store", {
      protects: ["credentials from the AI agent, generated code, logs, events and identity records"],
      verifies: [],
      requiresTrustIn: ["the Kido backend host and its operator", "the host environment"],
      doesNotProtectAgainst: ["a compromised Kido backend", "the cloud host", "anyone with host access"],
      version: "1",
      sourceRefs: ["bible §8, §27.3"],
    }),
    failureModes: ["secret not configured → fail closed"],
    limitations: ["the normal Kido backend sees plaintext"],
    sources: [],
    status: "VERIFIED_LIVE",
    statusNote: "built into Kido",
    knowledgePack: "platform/privacy",
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "chainlink-cre",
    displayName: "Chainlink Runtime Environment (CRE)",
    kind: "privacy",
    category: "confidential-compute",
    chains: ["ethereum-sepolia"],
    capabilities: ["CONFIDENTIAL_COMPUTE", "PRIVATE_API_ACCESS", "SECRET_ACCESS_CONTROL", "DECISION_ONLY_OUTPUT"],
    version: "unpinned",
    sdk: [],
    deployments: {},
    trust: trust("chainlink-cre", {
      protects: ["private inputs and API credentials during workflow execution, per CRE's confidential compute model"],
      verifies: ["workflow execution reported by the DON"],
      requiresTrustIn: ["Chainlink DON operators and enclave attestation", "workflow code"],
      doesNotProtectAgainst: ["a malicious workflow author", "disclosure the workflow itself performs"],
      version: "unpinned",
      sourceRefs: ["https://docs.chain.link/cre"],
    }),
    failureModes: ["DON unavailable", "simulation-only environment"],
    limitations: ["pending TRACE verification of confidential features on testnet"],
    sources: [{ url: "https://docs.chain.link/cre", retrieved: R }],
    status: "UNVERIFIED",
    statusNote: "awaiting TRACE report",
    knowledgePack: "privacy/chainlink-cre",
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "nautilus",
    displayName: "Nautilus (verifiable off-chain compute for Sui)",
    kind: "privacy",
    category: "confidential-compute",
    chains: ["sui-testnet"],
    capabilities: ["CONFIDENTIAL_COMPUTE", "VERIFIABLE_COMPUTE", "PRIVATE_API_ACCESS", "DECISION_ONLY_OUTPUT"],
    version: "unpinned",
    sdk: [],
    deployments: {},
    trust: trust("nautilus", {
      protects: ["computation and inputs inside an attested enclave"],
      verifies: ["enclave attestation checked on-chain"],
      requiresTrustIn: ["enclave hardware vendor", "enclave image reproducibility", "attestation verification package"],
      doesNotProtectAgainst: ["side channels outside the vendor's model", "a malicious enclave image that was approved"],
      version: "unpinned",
      sourceRefs: ["https://docs.sui.io/concepts/cryptography/nautilus"],
    }),
    failureModes: ["enclave unavailable", "attestation mismatch"],
    limitations: ["live use needs an attested enclave environment"],
    sources: [{ url: "https://docs.sui.io/concepts/cryptography/nautilus", retrieved: R }],
    status: "UNVERIFIED",
    statusNote: "awaiting TRACE report; live tier expected BLOCKED_ENV without an enclave host",
    knowledgePack: "privacy/nautilus",
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "seal",
    displayName: "Seal (decentralized secrets management for Sui)",
    kind: "privacy",
    category: "secret-access-control",
    chains: ["sui-testnet"],
    capabilities: ["SECRET_ACCESS_CONTROL", "ENCRYPTED_STATE"],
    version: "unpinned",
    sdk: [],
    deployments: {},
    trust: trust("seal", {
      protects: ["encrypted data readable only by parties an on-chain access policy approves"],
      verifies: ["access policy evaluated on-chain before key servers release shares"],
      requiresTrustIn: ["a threshold of key servers", "the access-policy Move package"],
      doesNotProtectAgainst: ["colluding key servers above threshold", "an authorized reader leaking plaintext"],
      version: "unpinned",
      sourceRefs: ["https://seal-docs.wal.app/"],
    }),
    failureModes: ["key servers unavailable", "policy denies access"],
    limitations: ["pending TRACE verification"],
    sources: [{ url: "https://seal-docs.wal.app/", retrieved: R }],
    status: "UNVERIFIED",
    statusNote: "awaiting TRACE report",
    knowledgePack: "privacy/seal",
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "aave-v3",
    displayName: "Aave v3",
    kind: "protocol",
    category: "lending",
    chains: ["ethereum-sepolia"],
    capabilities: ["LENDING_POSITION_STATE", "LENDING_REPAY", "LENDING_SUPPLY"],
    version: "v3 (Pool revision 1 on Sepolia)",
    sdk: [],
    deployments: {
      "ethereum-sepolia": {
        poolAddressesProvider: "0x012bAC54348C0E635dCAc9D5FB99f06F24136C9A",
        pool: "0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951",
        faucet: "0xC959483DBa39aa9E78757139af0e9a2EDEb3f42D",
        usdc: "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8",
      },
    },
    trust: trust("aave-v3", {
      protects: ["over-collateralized lending positions per Aave rules"],
      verifies: ["position health from on-chain reserve data and the Aave oracle"],
      requiresTrustIn: ["Aave governance and upgradeable Pool proxy", "Aave oracle", "Ethereum consensus"],
      doesNotProtectAgainst: ["oracle manipulation", "governance upgrades", "repaying someone else's debt unless the beneficiary is pinned"],
      version: "v3",
      sourceRefs: ["https://aave.com/docs/aave-v3/smart-contracts/pool", "bgd-labs/aave-address-book"],
    }),
    failureModes: ["reserve paused/frozen", "Pool proxy upgraded"],
    limitations: ["Sepolia accepts only Aave's own listed test assets (not Circle USDC)"],
    sources: [{ url: "https://aave.com/docs/aave-v3/smart-contracts/pool", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "addresses verified with cast on Sepolia",
    knowledgePack: "protocols/aave-v3",
    execution: [{ action: "REPAY", adapter: "aave-v3-repay", amaneAdapter: "AMANE_AAVE_V3_REPAY_V1", shipped: false }],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "uniswap-v3",
    displayName: "Uniswap v3",
    kind: "protocol",
    category: "dex",
    chains: ["ethereum-sepolia"],
    capabilities: ["DEX_QUOTE", "DEX_SWAP", "DEX_POOL_STATE"],
    version: "v3",
    sdk: [],
    deployments: {
      "ethereum-sepolia": {
        factory: "0x0227628f3F023bb0B980b67D528571c95c6DaC1c",
        swapRouter02: "0x3bFA4769FB09eefC5a80d6E87c3B9C650f7Ae48E",
        quoterV2: "0xEd1f6473345F45b75F8179591dd5bA1888cf2FB3",
        positionManager: "0x1238536071E1c677A632429e3655c799b22cDA52",
      },
    },
    trust: trust("uniswap-v3", {
      protects: ["constant-function swaps against pool liquidity"],
      verifies: ["swap output is what the pool pays; the caller enforces minimum output"],
      requiresTrustIn: ["pool liquidity providers (price)", "router contract"],
      doesNotProtectAgainst: ["price manipulation of thin pools — Amane's owner floor does", "sandwiching without a minimum output"],
      version: "v3",
      sourceRefs: ["https://developers.uniswap.org/"],
    }),
    failureModes: ["no liquidity", "price moved beyond floor"],
    limitations: ["SwapRouter02 exactInputSingle has no deadline; the adapter enforces it"],
    sources: [{ url: "https://developers.uniswap.org/", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "addresses verified with cast on Sepolia",
    knowledgePack: "protocols/uniswap-v3",
    execution: [{ action: "SWAP", adapter: "uniswap-v3-swap", amaneAdapter: "AMANE_UNISWAP_V3_SWAP_V1", shipped: false }],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "cetus-clmm",
    displayName: "Cetus CLMM",
    kind: "protocol",
    category: "dex",
    chains: ["sui-testnet"],
    capabilities: ["DEX_QUOTE", "DEX_SWAP", "DEX_POOL_STATE"],
    version: "testnet package_version 1 (source testnet-v0.0.2)",
    sdk: [],
    deployments: {
      "sui-testnet": {
        originalPackage: "0x5372d555ac734e272659136c2a0cd3227f9b92de67c80dc11250307268af2db8",
        publishedAt: "0x6bbdf09f9fa0baa1524080a5b8991042e95061c4e1206217279aec51ba08edf7",
        globalConfig: "0xc6273f844b4bc258952c4e477697aa12c918c8e08106fac6b934811298c9820a",
        pools: "0x20a086e6fa0741b3ca77d033a65faf0871349b986ddbdde6fa1d85d78a5f4222",
      },
    },
    trust: trust("cetus-clmm", {
      protects: ["concentrated-liquidity swaps against pool liquidity"],
      verifies: ["swap output delivered by flash_swap/repay_flash_swap"],
      requiresTrustIn: ["Cetus admins (emergency pause, mandatory version upgrades)", "pool liquidity providers"],
      doesNotProtectAgainst: ["thin-pool price moves — Amane's owner floor does", "forced version drift (adapter fails closed)"],
      version: "testnet v1",
      sourceRefs: ["https://github.com/CetusProtocol/cetus-contracts/tree/testnet"],
    }),
    failureModes: ["GlobalConfig version drift", "pool paused"],
    limitations: ["testnet lineage differs from mainnet; do not resolve by MVR name (F-0101)"],
    sources: [{ url: "https://cetus-1.gitbook.io/cetus-developer-docs", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "objects verified via Sui GraphQL",
    knowledgePack: "protocols/cetus-clmm",
    execution: [{ action: "SWAP", adapter: "cetus-clmm-swap", amaneAdapter: "AMANE_CETUS_CLMM_SWAP_V1", shipped: false }],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "amane",
    displayName: "Amane bounded financial authority",
    kind: "authority",
    category: "authority",
    chains: ["ethereum-sepolia", "sui-testnet"],
    capabilities: ["BOUNDED_EXECUTION", "LEASES", "PAUSE", "REVOKE", "RECOVERY_WITHDRAWAL"],
    version: "testnet release v1 (EVM account + Sui v4 package)",
    sdk: [{ package: "@amane/sdk", version: "0.1.0" }],
    deployments: {},
    trust: trust("amane", {
      protects: ["treasury funds from agents, relayers and a Kido backend that exceed the signed policy and lease"],
      verifies: ["Action ⊆ Lease ⊆ RootPolicy on-chain on each endpoint; delivery measured by the account"],
      requiresTrustIn: ["root controller keys", "Amane core code (not audited)", "each chain's consensus", "adapter code and the upstream protocol it calls"],
      doesNotProtectAgainst: ["a compromised root controller", "spending the remaining per-endpoint budget during a revocation race", "upstream protocol failure"],
      version: "v1",
      sourceRefs: ["Aname/README.md", "Aname/deployments/testnet.json"],
    }),
    failureModes: ["lease expired/revoked", "account paused", "RPC outage (operational, not a policy verdict)"],
    limitations: ["testnet prototype, not audited", "v1 ships PAY; SWAP/REPAY adapters pending"],
    sources: [],
    status: "VERIFIED_LIVE",
    statusNote: "live two-chain gauntlet 40/40; deployments read from the Amane manifest",
    knowledgePack: "platform/amane",
    execution: [{ action: "PAY", adapter: "amane-transfer-pay", amaneAdapter: "Transfer Pay v1", shipped: true }],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "mock-transport",
    displayName: "Mock cross-chain transport",
    kind: "transport",
    category: "bridge",
    chains: ["ethereum-sepolia", "sui-testnet"],
    capabilities: ["TOKEN_TRANSFER", "MESSAGE", "DELIVERY_PROOF"],
    version: "1",
    sdk: [],
    deployments: {},
    trust: trust("mock-transport", { protects: [], verifies: [], requiresTrustIn: ["test harness"], doesNotProtectAgainst: ["everything — test only"], version: "1", sourceRefs: [] }),
    failureModes: ["configurable: timeout, duplicate, mutation"],
    limitations: ["simulation and tests only"],
    sources: [],
    status: "MOCK_ONLY",
    statusNote: "never used for a live claim",
    knowledgePack: "transport/mock",
  },
  ...(["wormhole", "layerzero"] as const).map(
    (id): ProviderManifest => ({
      schemaVersion: "kido.provider/v1",
      providerId: id,
      displayName: id === "wormhole" ? "Wormhole" : "LayerZero",
      kind: "transport",
      category: "bridge",
      chains: ["ethereum-sepolia", "sui-testnet"],
      capabilities: ["TOKEN_TRANSFER", "MESSAGE", "DELIVERY_PROOF"],
      version: "unpinned",
      sdk: [],
      deployments: {},
      trust: trust(id, {
        protects: ["message/asset delivery per the transport's verification model"],
        verifies: ["delivery attestation by the transport's verifiers"],
        requiresTrustIn: [id === "wormhole" ? "Wormhole guardian set" : "configured LayerZero DVNs and executor"],
        doesNotProtectAgainst: ["verifier compromise", "destination semantics — Kido/Amane revalidate on arrival"],
        version: "unpinned",
        sourceRefs: [],
      }),
      failureModes: ["delivery timeout", "duplicate delivery"],
      limitations: ["transport is never authority", "testnet route pending TRACE verification"],
      sources: [],
      status: "UNVERIFIED",
      statusNote: "awaiting TRACE report",
      knowledgePack: `transport/${id}`,
    }),
  ),
];
