import type { ProviderManifest, TrustProfile } from "../types.js";

const R = "2026-09-26";
const trust = (providerId: string, t: Omit<TrustProfile, "providerId">): TrustProfile => ({ providerId, ...t });

/**
 * Seed provider manifests. Facts marked VERIFIED_* were checked by TRACE against live testnets or
 * official documentation (`.gauntlet/research/`); UNVERIFIED entries may be selected for planning
 * and simulation but never counted as live capability.
 */
export const PROVIDERS: ProviderManifest[] = [
  {
    schemaVersion: "kido.provider/v1",
    providerId: "ens",
    displayName: "ENS (Ethereum Name Service)",
    aliases: ["ens"],
    kind: "identity",
    category: "nameservice",
    chains: ["ethereum-sepolia"],
    capabilities: ["RESOLVE", "REVERSE_RESOLVE", "REGISTER", "SUBNAME", "TEXT_RECORDS", "ADDRESS_RECORD", "SCOPED_RECORD_MANAGER", "REVOKE", "EXPIRY"],
    version: "ensv2-beta (Sepolia)",
    sdk: [],
    deployments: {
      "ethereum-sepolia": {
        rootRegistry: "0x9703dbd26dab89504490994138cf2c575251a9ce",
        ethRegistry: "0x657ea849311d3d5823348dded7c2aaafb3ede09e",
        ethRegistrar: "0xabe76f6c8dfced81aa5a2bb8034202a7136b94ca",
        universalResolver: "0xeEeEEEeE14D718C2B47D9923Deab1335E144EeEe",
        rentPriceOracle: "0x9b0b9c65bdaf9794ff7697e4dcfb1f50581072bb",
        verifiableFactory: "0x9e726eb570beb6bceb495ab8cda7df517d4e841c",
        permissionedResolverImpl: "0x14f09fd05d4585759e54844dc9b00147131cf243",
        userRegistryImpl: "0xa80338aaa8d23831cea25e858d1774534abb0263",
        mockUsdc: "0x16f95d91dba7da3aca778ec053df0ff6c6a8aa8e",
        legacyRegistry: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
        legacyPublicResolver: "0xE99638b40E4Fff0129D56f03b55b6bbC4BBE49b5",
        legacyNameWrapper: "0x0635513f179D50A207757E05759CbD106d7dFcE8",
      },
    },
    trust: trust("ens", {
      protects: ["human-readable binding of a name to records chosen by the name's controller"],
      verifies: ["record values are what the resolver returns for the current name owner/manager"],
      requiresTrustIn: ["name owner and delegated record managers", "resolver contract", "Ethereum consensus", "the RPC used to read it"],
      doesNotProtectAgainst: ["a compromised name owner rewriting records", "stale off-chain caches", "financial misuse — ENS grants no financial authority"],
      version: "ensv2-beta",
      sourceRefs: ["https://docs.ens.domains/ensv2/overview/", "https://docs.ens.domains/ensip/26/"],
    }),
    failureModes: ["resolver not found", "name expired", "ENSv2 interfaces change during beta"],
    limitations: [
      "ENSv2 is beta on Sepolia; ENSIP-25/26 are draft standards",
      "ENSv1 cannot mint new names on Sepolia (controller de-authorised)",
      "registration: commit-reveal (>=60 s), >=28 days, 5+ chars = 8 USDC/yr paid in ENSv2 MockUSDC — not Aave test USDC",
      "records use setText(bytes dnsName, key, value); a scoped setter can write that key on every name the resolver serves, so each agent gets its own resolver",
      "subnames need a UserRegistry proxy per parent (setSubregistry → setParent → register)",
    ],
    sources: [{ url: "https://docs.ens.domains/ensv2/overview/", retrieved: R }, { url: "https://github.com/ensdomains/contracts-v2", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "contracts verified live on Sepolia (TRACE 2026-09-26); ABIs from ensdomains/contracts-v2@71a3b733",
    knowledgePack: "identity/ens",
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "suins",
    displayName: "SuiNS",
    aliases: ["suins"],
    kind: "identity",
    category: "nameservice",
    chains: ["sui-testnet"],
    capabilities: ["RESOLVE", "REVERSE_RESOLVE", "REGISTER", "SUBNAME", "TEXT_RECORDS", "ADDRESS_RECORD", "EXPIRY"],
    version: "core v5 / subnames v2 (testnet)",
    sdk: [{ package: "@mysten/suins", version: "2.0.12" }],
    deployments: {
      "sui-testnet": {
        coreOriginal: "0x22fa05f21b1ad71442491220bb9338f7b7095fe35000ef88d5400d28523bdd93",
        coreLatest: "0x40eee27b014a872f5c3330dcd5329aa55c7fe0fcc6e70c6498852e2e3727172e",
        suins: "0x300369e8909b9a6464da265b9a5a9ab6fe2158a040e84e808628cde7a07ee5a3",
        subnamesLatest: "0xf0c12144cb6e237a28b75368fd7a03fb2c484923a4b471da96e059f9e34edce7",
        payments: "0x4f33a0e1e30530f2aa500a41b9e3d502f8af3ef2c20bd0a1e42374e329da7cb0",
      },
    },
    trust: trust("suins", {
      protects: ["human-readable binding of a Sui name to a target address and records"],
      verifies: ["current target/records of the name object"],
      requiresTrustIn: ["name NFT holder", "SuiNS packages and their upgrade authority", "Sui consensus"],
      doesNotProtectAgainst: ["compromised name holder", "financial misuse — SuiNS grants no financial authority"],
      version: "unpinned",
      sourceRefs: ["https://docs.suins.io/"],
    }),
    failureModes: ["name expired", "target unset"],
    limitations: [
      "records are limited to avatar, content_hash and walrus_site_id — no free-form agent text records",
      "registration pays in test USDC/NS or SUI via Pyth; testnet USDC/NS mint caps are not ours",
      "the SDK still references subnames v1; v2 is live (F-0406)",
    ],
    sources: [{ url: "https://docs.suins.io/", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "reads verified live with @mysten/suins 2.0.12 over gRPC (TRACE 2026-09-26)",
    capabilityStatus: {
      REGISTER: { status: "BLOCKED_ENV", note: "BC-SUINS-1: needs test USDC/NS or a Pyth access token" },
      SUBNAME: { status: "BLOCKED_ENV", note: "requires owning a parent name (blocked by BC-SUINS-1)" },
    },
    knowledgePack: "identity/suins",
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "kido-secret-store",
    displayName: "Kido host secret store",
    aliases: ["secret store", "kido"],
    kind: "privacy",
    category: "secrets",
    chains: ["ethereum-sepolia", "sui-testnet"],
    capabilities: ["SECRET_STORAGE"],
    version: "1",
    sdk: [],
    deployments: {},
    trust: trust("kido-secret-store", {
      protects: ["credentials from the AI agent, generated code, logs, events and identity records"],
      verifies: [],
      requiresTrustIn: ["the Kido backend host and its operator", "the host environment"],
      doesNotProtectAgainst: ["a compromised Kido backend", "the cloud host", "anyone with host access"],
      version: "1",
      sourceRefs: ["bible §8, §27.3"],
    }),
    failureModes: ["secret not configured → fail closed"],
    limitations: ["the normal Kido backend sees plaintext"],
    sources: [],
    status: "VERIFIED_LIVE",
    statusNote: "built into Kido",
    knowledgePack: "platform/privacy",
    plaintextVisibleTo: ["NORMAL_KIDO_BACKEND", "CLOUD_HOST"],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "chainlink-cre",
    displayName: "Chainlink Runtime Environment (CRE)",
    aliases: ["chainlink", "cre"],
    kind: "privacy",
    category: "confidential-compute",
    chains: ["ethereum-sepolia"],
    capabilities: ["CONFIDENTIAL_COMPUTE", "PRIVATE_API_ACCESS", "SECRET_ACCESS_CONTROL", "DECISION_ONLY_OUTPUT"],
    version: "cre-sdk 1.22.0 / cre CLI v1.35.0",
    sdk: [{ package: "@chainlink/cre-sdk", version: "1.22.0" }],
    deployments: { "ethereum-sepolia": { keystoneForwarder: "0xF8344CFd5c43616a4366C34E3EEE75af79a74482", mockForwarder: "0x15fC6ae953E024d975e77382eEeC56A9101f9F88", kidoReceiverMockForwarder: "0x41032ee6b7a635b16ead62d0bcc20a9be05a5164" } },
    trust: trust("chainlink-cre", {
      protects: ["private inputs and API credentials during workflow execution, per CRE's confidential compute model"],
      verifies: ["workflow execution reported by the DON"],
      requiresTrustIn: ["Chainlink DON operators and enclave attestation", "workflow code"],
      doesNotProtectAgainst: ["a malicious workflow author", "disclosure the workflow itself performs"],
      version: "unpinned",
      sourceRefs: ["https://docs.chain.link/cre"],
    }),
    failureModes: ["DON unavailable", "simulation-only environment"],
    limitations: ["early access: deploy needs organisation approval", "confidential (TEE) workflows are an invite-only beta; simulation runs on one node without a TEE and must be labelled SIMULATED", "receiver contracts must implement onReport(bytes,bytes) + ERC-165"],
    sources: [{ url: "https://docs.chain.link/cre", retrieved: R }],
    status: "BLOCKED_ENV",
    statusNote: "BE-CRE-1..3: interactive cre login, org deploy approval and confidential beta invite required; sdk 1.22.0 / CLI v1.35.0",
    knowledgePack: "privacy/chainlink-cre",
    plaintextVisibleTo: [],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "nautilus",
    displayName: "Nautilus (verifiable off-chain compute for Sui)",
    aliases: ["nautilus"],
    kind: "privacy",
    category: "confidential-compute",
    chains: ["sui-testnet"],
    capabilities: ["CONFIDENTIAL_COMPUTE", "VERIFIABLE_COMPUTE", "PRIVATE_API_ACCESS", "DECISION_ONLY_OUTPUT"],
    version: "MystenLabs/nautilus@0104d627 (no npm package)",
    sdk: [],
    deployments: { "sui-testnet": { attestationModule: "0x2::nitro_attestation" } },
    trust: trust("nautilus", {
      protects: ["computation and inputs inside an attested enclave"],
      verifies: ["enclave attestation checked on-chain"],
      requiresTrustIn: ["enclave hardware vendor", "enclave image reproducibility", "attestation verification package"],
      doesNotProtectAgainst: ["side channels outside the vendor's model", "a malicious enclave image that was approved"],
      version: "unpinned",
      sourceRefs: ["https://docs.sui.io/concepts/cryptography/nautilus"],
    }),
    failureModes: ["enclave unavailable", "attestation mismatch"],
    limitations: ["AWS Nitro enclave framework; live use needs an attested Nitro (or Oyster) host", "on-chain sui::nitro_attestation verification is live"],
    sources: [{ url: "https://docs.sui.io/concepts/cryptography/nautilus", retrieved: R }, { url: "https://github.com/MystenLabs/nautilus", retrieved: R }],
    status: "BLOCKED_ENV",
    statusNote: "BE-NAUT-1: no AWS Nitro host; local Move fixtures and on-chain attestation rejection verified",
    knowledgePack: "privacy/nautilus",
    plaintextVisibleTo: [],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "seal",
    displayName: "Seal (decentralized secrets management for Sui)",
    aliases: ["seal"],
    kind: "privacy",
    category: "secret-access-control",
    chains: ["sui-testnet"],
    capabilities: ["SECRET_ACCESS_CONTROL", "ENCRYPTED_STATE"],
    version: "package v6 (testnet)",
    sdk: [{ package: "@mysten/seal", version: "1.4.16" }],
    deployments: {
      "sui-testnet": {
        packageLatest: "0xdccbeb87767be2b2346af5575eb139807205e4c23ec53dc616f951fe1d814112",
        packageOriginal: "0x4614e5da0136ee7d464992ddd3719d388ae2bfdb48dfec6d9ad579f87341f2e1",
        keyServerMysten1: "0x73d05d62c18d9374e3ea529e8e0ed6161da1a141a94d3f76ae3fe4e99356db75",
        keyServerMysten2: "0xf5d14a81a982144ae441cd7d64b09027f116a468bd36e7eca494f750591623c8",
        committee3of5: "0xb012378c9f3799fb5b1a7083da74a4069e3c3f1c93de0b27212a5799ce1e1e98",
        kidoReaderPolicyPackage: "0x7ca5b0ee2b1c7eec39e853078911532fab0c87398d9eaf5552eb7cd53ea3e022",
      },
    },
    parameters: { keyServers: "keyServerMysten1,keyServerMysten2", threshold: 2, policyModule: "reader_policy" },
    trust: trust("seal", {
      protects: ["encrypted data readable only by parties an on-chain access policy approves"],
      verifies: ["access policy evaluated on-chain before key servers release shares"],
      requiresTrustIn: ["a threshold of key servers", "the access-policy Move package"],
      doesNotProtectAgainst: ["colluding key servers above threshold", "an authorized reader leaking plaintext"],
      version: "unpinned",
      sourceRefs: ["https://seal-docs.wal.app/"],
    }),
    failureModes: ["key servers unavailable", "policy denies access"],
    limitations: ["access policies are seal_approve* Move entry functions owned by the integrator", "does not compute on secrets — only controls who may decrypt"],
    sources: [{ url: "https://seal-docs.wal.app/", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "testnet key servers and SDK 1.4.16 over gRPC verified (TRACE 2026-09-26)",
    knowledgePack: "privacy/seal",
    plaintextVisibleTo: [],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "aave-v3",
    displayName: "Aave v3",
    aliases: ["aave"],
    kind: "protocol",
    category: "lending",
    chains: ["ethereum-sepolia"],
    capabilities: ["LENDING_POSITION_STATE", "LENDING_REPAY", "LENDING_SUPPLY"],
    version: "v3 (Pool revision 1 on Sepolia)",
    sdk: [],
    deployments: {
      "ethereum-sepolia": {
        poolAddressesProvider: "0x012bAC54348C0E635dCAc9D5FB99f06F24136C9A",
        pool: "0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951",
        faucet: "0xC959483DBa39aa9E78757139af0e9a2EDEb3f42D",
        usdc: "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8",
        aUsdc: "0x16dA4541aD1807f4443d92D26044C1147406EB80",
        variableDebtUsdc: "0x36B5dE936eF1710E1d22EabE5231b28581a92ECc",
        dataProvider: "0x3e9708d80f7B3e43118013075F7e95CE3AB31F31",
      },
    },
    trust: trust("aave-v3", {
      protects: ["over-collateralized lending positions per Aave rules"],
      verifies: ["position health from on-chain reserve data and the Aave oracle"],
      requiresTrustIn: ["Aave governance and upgradeable Pool proxy", "Aave oracle", "Ethereum consensus"],
      doesNotProtectAgainst: ["oracle manipulation", "governance upgrades", "repaying someone else's debt unless the beneficiary is pinned"],
      version: "v3",
      sourceRefs: ["https://aave.com/docs/aave-v3/smart-contracts/pool", "bgd-labs/aave-address-book"],
    }),
    failureModes: ["reserve paused/frozen", "Pool proxy upgraded"],
    limitations: ["Sepolia accepts only Aave's own listed test assets (not Circle USDC)", "Sepolia runs an old v3.0 Pool (revision 1), not the v3.3 in current docs", "repay(asset, amount, rateMode=2, onBehalfOf); max-uint for another's debt reverts \"40\"", "measure repayment by variableDebtToken.balanceOf(beneficiary) before/after"],
    sources: [{ url: "https://aave.com/docs/aave-v3/smart-contracts/pool", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "addresses verified with cast on Sepolia",
    knowledgePack: "protocols/aave-v3",
    execution: [{ action: "REPAY", capability: "LENDING_REPAY", adapter: "aave-v3-repay", amaneAdapter: "Aave V3 Repay", shipped: true }],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "uniswap-v3",
    displayName: "Uniswap v3",
    aliases: ["uniswap"],
    kind: "protocol",
    category: "dex",
    chains: ["ethereum-sepolia"],
    capabilities: ["DEX_QUOTE", "DEX_SWAP", "DEX_POOL_STATE"],
    version: "v3",
    sdk: [],
    deployments: {
      "ethereum-sepolia": {
        factory: "0x0227628f3F023bb0B980b67D528571c95c6DaC1c",
        swapRouter02: "0x3bFA4769FB09eefC5a80d6E87c3B9C650f7Ae48E",
        quoterV2: "0xEd1f6473345F45b75F8179591dd5bA1888cf2FB3",
        positionManager: "0x1238536071E1c677A632429e3655c799b22cDA52",
      },
    },
    trust: trust("uniswap-v3", {
      protects: ["constant-function swaps against pool liquidity"],
      verifies: ["swap output is what the pool pays; the caller enforces minimum output"],
      requiresTrustIn: ["pool liquidity providers (price)", "router contract"],
      doesNotProtectAgainst: ["price manipulation of thin pools — Amane's owner floor does", "sandwiching without a minimum output"],
      version: "v3",
      sourceRefs: ["https://developers.uniswap.org/"],
    }),
    failureModes: ["no liquidity", "price moved beyond floor"],
    limitations: ["SwapRouter02 exactInputSingle has no deadline; wrap in multicall(deadline, …) or enforce in the adapter", "existing Sepolia pools have arbitrary prices; create a project pool", "fee tiers 100/500/3000/10000"],
    sources: [{ url: "https://developers.uniswap.org/", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "addresses verified with cast on Sepolia",
    knowledgePack: "protocols/uniswap-v3",
    execution: [{ action: "SWAP", capability: "DEX_SWAP", adapter: "uniswap-v3-swap", amaneAdapter: "Uniswap V3 Swap", shipped: true }],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "cetus-clmm",
    displayName: "Cetus CLMM",
    aliases: ["cetus"],
    kind: "protocol",
    category: "dex",
    chains: ["sui-testnet"],
    capabilities: ["DEX_QUOTE", "DEX_SWAP", "DEX_POOL_STATE"],
    version: "testnet package_version 1 (source testnet-v0.0.2)",
    sdk: [],
    deployments: {
      "sui-testnet": {
        originalPackage: "0x5372d555ac734e272659136c2a0cd3227f9b92de67c80dc11250307268af2db8",
        publishedAt: "0x6bbdf09f9fa0baa1524080a5b8991042e95061c4e1206217279aec51ba08edf7",
        globalConfig: "0xc6273f844b4bc258952c4e477697aa12c918c8e08106fac6b934811298c9820a",
        pools: "0x20a086e6fa0741b3ca77d033a65faf0871349b986ddbdde6fa1d85d78a5f4222",
      },
    },
    trust: trust("cetus-clmm", {
      protects: ["concentrated-liquidity swaps against pool liquidity"],
      verifies: ["swap output delivered by flash_swap/repay_flash_swap"],
      requiresTrustIn: ["Cetus admins (emergency pause, mandatory version upgrades)", "pool liquidity providers"],
      doesNotProtectAgainst: ["thin-pool price moves — Amane's owner floor does", "forced version drift (adapter fails closed)"],
      version: "testnet v1",
      sourceRefs: ["https://github.com/CetusProtocol/cetus-contracts/tree/testnet"],
    }),
    failureModes: ["GlobalConfig version drift", "pool paused"],
    limitations: ["testnet lineage differs from mainnet; do not resolve by MVR name (F-0101)", "create_pool_v2 aborts on testnet (code 6, deprecated); use create_pool_v3 (F-0401)"],
    sources: [{ url: "https://cetus-1.gitbook.io/cetus-developer-docs", retrieved: R }],
    status: "VERIFIED_LIVE",
    statusNote: "objects verified via Sui GraphQL",
    knowledgePack: "protocols/cetus-clmm",
    execution: [{ action: "SWAP", capability: "DEX_SWAP", adapter: "cetus-clmm-swap", amaneAdapter: "Cetus CLMM Swap", shipped: true }],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "amane",
    displayName: "Amane bounded financial authority",
    aliases: ["amane"],
    kind: "authority",
    category: "authority",
    chains: ["ethereum-sepolia", "sui-testnet"],
    capabilities: ["BOUNDED_EXECUTION", "LEASES", "PAUSE", "REVOKE", "RECOVERY_WITHDRAWAL"],
    version: "testnet release v1 (EVM account + Sui v4 package)",
    sdk: [{ package: "@amane/sdk", version: "0.1.0" }],
    deployments: {},
    trust: trust("amane", {
      protects: ["treasury funds from agents, relayers and a Kido backend that exceed the signed policy and lease"],
      verifies: ["Action ⊆ Lease ⊆ RootPolicy on-chain on each endpoint; delivery measured by the account"],
      requiresTrustIn: ["root controller keys", "Amane core code (not audited)", "each chain's consensus", "adapter code and the upstream protocol it calls"],
      doesNotProtectAgainst: ["a compromised root controller", "spending the remaining per-endpoint budget during a revocation race", "upstream protocol failure"],
      version: "v1",
      sourceRefs: ["Aname/README.md", "Aname/deployments/testnet.json"],
    }),
    failureModes: ["lease expired/revoked", "account paused", "RPC outage (operational, not a policy verdict)"],
    limitations: ["testnet prototype, not audited", "EVM core v2 (new accounts) enforces REPAY; v1 accounts and the Sui core enforce SWAP and PAY", "adapters: Transfer Pay (both), Uniswap V3 Swap and Aave V3 Repay (Sepolia), Cetus CLMM Swap (Sui)"],
    sources: [],
    status: "VERIFIED_LIVE",
    statusNote: "live two-chain gauntlet 40/40; deployments read from the Amane manifest",
    knowledgePack: "platform/amane",
    deploymentManifestRef: "Aname/deployments/testnet.json",
    execution: [{ action: "PAY", capability: "BOUNDED_EXECUTION", adapter: "amane-transfer-pay", amaneAdapter: "Transfer Pay", shipped: true }],
  },
  {
    schemaVersion: "kido.provider/v1",
    providerId: "mock-transport",
    displayName: "Mock cross-chain transport",
    aliases: ["mock transport"],
    kind: "transport",
    category: "bridge",
    chains: ["ethereum-sepolia", "sui-testnet"],
    capabilities: ["TOKEN_TRANSFER", "MESSAGE", "DELIVERY_PROOF"],
    version: "1",
    sdk: [],
    deployments: {},
    trust: trust("mock-transport", { protects: [], verifies: [], requiresTrustIn: ["test harness"], doesNotProtectAgainst: ["everything — test only"], version: "1", sourceRefs: [] }),
    failureModes: ["configurable: timeout, duplicate, mutation"],
    limitations: ["simulation and tests only"],
    sources: [],
    status: "MOCK_ONLY",
    statusNote: "never used for a live claim",
    knowledgePack: "transport/mock",
  },
  ...(["wormhole", "layerzero"] as const).map(
    (id): ProviderManifest => ({
      schemaVersion: "kido.provider/v1",
      providerId: id,
      displayName: id === "wormhole" ? "Wormhole" : "LayerZero",
    aliases: [id],
      kind: "transport",
      category: "bridge",
      chains: ["ethereum-sepolia", "sui-testnet"],
      capabilities: ["TOKEN_TRANSFER", "MESSAGE", "DELIVERY_PROOF"],
      version: id === "wormhole" ? "sdk 6.1.5" : "EndpointV2 (EID 40161 / 40378)",
      sdk: id === "wormhole" ? [{ package: "@wormhole-foundation/sdk", version: "6.1.5" }] : [{ package: "@layerzerolabs/lz-v2-utilities", version: "3.0.168" }],
      deployments: id === "wormhole"
        ? { "ethereum-sepolia": { core: "0x4a8bc80Ed5a4067f1CCf107057b8270E0cC11A78", tokenBridge: "0xDB5492265f6038831E89f495670FF909aDe94bd9" }, "sui-testnet": { coreState: "0x31358d198147da50db32eda2562951d53973a0c0ad5ed738e9b17d88b213d790", tokenBridgeState: "0x6fb10cdb7aa299e9a4308752dadecb049ff55a892de92992a1edbd7912b3d6da" } }
        : { "ethereum-sepolia": { endpointV2: "0x6EDCE65403992e310A62460808c4b910D972f10f" }, "sui-testnet": { endpointPackage: "0xabf9629418d997fcc742a5ca22820241b72fb53691f010bc964eb49b4bd2263a", endpointObject: "0x2b96537c30c5fa962a1bfb58a168fc17c17f2546c88e2e9252f21ee7d5eff57a" } },
      trust: trust(id, {
        protects: ["message/asset delivery per the transport's verification model"],
        verifies: ["delivery attestation by the transport's verifiers"],
        requiresTrustIn: [id === "wormhole" ? "Wormhole guardian set" : "configured LayerZero DVNs and executor"],
        doesNotProtectAgainst: ["verifier compromise", "destination semantics — Kido/Amane revalidate on arrival"],
        version: "unpinned",
        sourceRefs: [],
      }),
      failureModes: ["delivery timeout", "duplicate delivery"],
      limitations: id === "wormhole"
        ? ["transport is never authority", "Sepolia↔Sui testnet route via Token Bridge with manual redeem; single testnet guardian", "NTT requires self-deployment and core exactly 6.1.4"]
        : ["transport is never authority", "Sepolia→Sui pathway supported but no ready token route (own OFT pair needed)", "Sui SDK depends on @mysten/sui 1.x JSON-RPC, which is shut down (F-0407)"],
      sources: [],
      status: id === "wormhole" ? "VERIFIED_DOCS" : "BLOCKED_ENV",
      statusNote: id === "wormhole" ? "core/token-bridge state verified live on both chains; no live transfer run yet (BE-WH-1)" : "BE-LZ-1: Sui SDK unusable without JSON-RPC",
      knowledgePack: `transport/${id}`,
    }),
  ),
];
