import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { AMANE_CODES } from '../src/codes.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const body = Object.entries(AMANE_CODES)
  .map(([k, v]) => `    uint16 internal constant ${k.replace(/^AMANE_/, '')} = ${v};`)
  .join('\n');
writeFileSync(
  resolve(root, 'evm/src/AmaneCodes.sol'),
  `// SPDX-License-Identifier: MIT
// Generated by packages/core/scripts/generate-codes.ts from packages/core/src/codes.ts. Do not edit.
pragma solidity 0.8.28;

/// Rejection codes shared with the Sui core's abort codes and the SDK.
library Codes {
${body}
}
`,
);
console.log('wrote evm/src/AmaneCodes.sol');
