import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const read = (file: string, name: string) => JSON.parse(readFileSync(resolve(root, `evm/out/${file}/${name}.json`), 'utf8'));

const account = read('AmaneAccount.sol', 'AmaneAccount');
const registry = read('AdapterRegistry.sol', 'AdapterRegistry');
const token = read('AmaneTestToken.sol', 'AmaneTestToken');
const aaveRepay = read('AaveV3RepayAdapter.sol', 'AaveV3RepayAdapter');
const uniSwap = read('UniswapV3SwapAdapter.sol', 'UniswapV3SwapAdapter');

const out = `// Generated by packages/sdk/scripts/export-evm-artifacts.ts from evm/out. Do not edit.
export const amaneAccountAbi = ${JSON.stringify(account.abi)} as const;
export const amaneAccountBytecode = '${account.bytecode.object}' as const;
export const adapterRegistryAbi = ${JSON.stringify(registry.abi)} as const;
export const amaneTestTokenAbi = ${JSON.stringify(token.abi)} as const;
export const amaneTestTokenBytecode = '${token.bytecode.object}' as const;
export const aaveV3RepayAdapterAbi = ${JSON.stringify(aaveRepay.abi)} as const;
export const aaveV3RepayAdapterBytecode = '${aaveRepay.bytecode.object}' as const;
export const uniswapV3SwapAdapterAbi = ${JSON.stringify(uniSwap.abi)} as const;
export const uniswapV3SwapAdapterBytecode = '${uniSwap.bytecode.object}' as const;
`;
writeFileSync(resolve(root, 'packages/sdk/src/evm-artifacts.ts'), out);
console.log('wrote packages/sdk/src/evm-artifacts.ts');
