import type { StudioTemplate } from "../types.js";

/**
 * The non-security modules: the protocol adapter, the agent runtime, tests and project scaffolding.
 *
 * These carry the strategy, which genuinely varies per agent. They still do not get to make
 * security decisions — the adapter builds calldata and the runtime describes intents, but neither
 * one authorizes anything.
 */

const header = (what: string) => `/**
 * ${what}
 *
 * GENERATED by ContextLock Studio from a versioned Blueprint.
 */
`;

export const protocolAdapterTemplate: StudioTemplate = {
  id: "aave-adapter",
  version: 1,
  moduleKind: "protocol-adapter",
  reusesContextLockCore: false,
  render: (bp) => {
    const proto = bp.protocols[0]!;
    return [
      {
        path: `src/adapters/${proto.id}.ts`,
        content: `${header(`${proto.displayName} action adapter.`)}
import type { Address } from "../contextlock/types.js";

/**
 * Typed actions only. There is deliberately no buildArbitraryCall(): a generic adapter would hand
 * back exactly the ambient authority the capability model removes, and it would do so through an
 * interface that looks helpful.
 */
export type SupportedAction = ${bp.actions.map((a) => JSON.stringify(a.kind)).join(" | ")};

export const SUPPORTED_ACTIONS: readonly SupportedAction[] = ${JSON.stringify(bp.actions.map((a) => a.kind))};

export interface ActionIntent {
  kind: SupportedAction;
  amount: bigint;
  /** Constrained by the Blueprint's recipient policy; see assertRecipientAllowed. */
  recipient: Address;
}

${bp.actions
  .map(
    (a) => `/**
 * ${a.displayName}
 * target: ${a.targetPolicy.mode}${a.targetPolicy.mode === "protocol-resolved" ? ` (${a.targetPolicy.protocolRef}.${a.targetPolicy.contractRole})` : ""}
 * recipient: ${a.recipientPolicy.mode}
 */
export const ${a.id.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())}Action = {
  kind: ${JSON.stringify(a.kind)},
  targetMode: ${JSON.stringify(a.targetPolicy.mode)},
  recipientMode: ${JSON.stringify(a.recipientPolicy.mode)},
  approvals: ${JSON.stringify(a.approvals)},
} as const;`,
  )
  .join("\n\n")}

/**
 * Recipient policy, enforced locally as a first line only.
 *
 * The executor re-checks this on-chain, which is what actually protects the user. This check exists
 * so a bug surfaces in the agent's own tests rather than as a revert nobody expected.
 */
export function assertRecipientAllowed(intent: ActionIntent, selfAddress: Address): void {
${bp.actions
  .filter((a) => a.recipientPolicy.mode === "self-only")
  .map(
    (a) => `  if (intent.kind === ${JSON.stringify(a.kind)} && intent.recipient.toLowerCase() !== selfAddress.toLowerCase()) {
    throw new Error(\`RecipientNotAllowed: \${${JSON.stringify(a.kind)}} may only pay the position owner\`);
  }`,
  )
  .join("\n")}
}

/** Unlimited approvals are not representable: every approval is bounded by the action amount. */
export function approvalAmountFor(intent: ActionIntent): bigint {
  return intent.amount;
}
`,
      },
    ];
  },
};

export const agentRuntimeTemplate: StudioTemplate = {
  id: "generic-defi-agent",
  version: 1,
  moduleKind: "agent-runtime",
  reusesContextLockCore: false,
  render: (bp) => [
    {
      path: "src/agent/runtime.ts",
      content: `${header("Agent runtime — untrusted by design.")}
import { buildCapabilityRequest, type AgentIntent } from "../contextlock/core.js";
import { assertRecipientAllowed } from "../adapters/${bp.protocols[0]!.id}.js";
import type { Address } from "../contextlock/types.js";

/**
 * This runtime is assumed compromised.
 *
 * It holds no key, signs nothing and submits nothing. It observes state, decides what it would like
 * to happen, and asks. Everything that could turn that request into money moving lives elsewhere
 * and re-checks the request independently.
 *
 * Objective: ${bp.objective}
 */
export interface AgentObservation {
  healthFactorBps: number;
  observedAtUnix: number;
}

export interface BrokerClient {
  requestCapability(req: ReturnType<typeof buildCapabilityRequest>): Promise<{
    status: "ISSUED" | "ESCALATED" | "DENIED";
    reasonCode: string;
  }>;
}

export class GuardianAgent {
  constructor(
    private readonly broker: BrokerClient,
    private readonly selfAddress: Address,
  ) {}

  /**
   * The trigger threshold is NOT here.
   *
   * It is confidential and is evaluated inside the confidential handler. If the agent held it, an
   * attacker who compromised the agent would learn it, and an agent that could compare against it
   * locally could be talked into skipping the comparison.
   */
  async considerAction(obs: AgentObservation, proposed: AgentIntent): Promise<string> {
    assertRecipientAllowed(
      { kind: proposed.actionKind, amount: proposed.amount, recipient: proposed.recipient },
      this.selfAddress,
    );

    const req = buildCapabilityRequest(proposed, \`\${obs.observedAtUnix}-\${proposed.actionKind}\`);
    const res = await this.broker.requestCapability(req);

    // The agent does not get to disagree with the verdict, retry it under a different framing, or
    // decompose a refused action into smaller permitted ones. It reports and stops.
    switch (res.status) {
      case "ISSUED":
        return \`authorized: \${res.reasonCode}\`;
      case "ESCALATED":
        return \`awaiting human approval: \${res.reasonCode}\`;
      case "DENIED":
        return \`refused: \${res.reasonCode}\`;
    }
  }
}
`,
    },
  ],
};

export const testsTemplate: StudioTemplate = {
  id: "tests",
  version: 1,
  moduleKind: "tests",
  reusesContextLockCore: false,
  render: (bp) => [
    {
      path: "test/security.test.ts",
      content: `${header("Generated security tests.")}
import { describe, it, expect } from "vitest";
import { mayProceed, requiresHumanApproval } from "../src/ledger/escalation.js";
import { assertRecipientAllowed, SUPPORTED_ACTIONS } from "../src/adapters/${bp.protocols[0]!.id}.js";
import { CAPABILITY_BINDINGS, CAPABILITY_TTL_SECONDS } from "../src/contextlock/core.js";

const SELF = "0x0000000000000000000000000000000000005e1f" as const;
const ATTACKER = "0x000000000000000000000000000000000000dead" as const;

describe("capability binding", () => {
  it("binds every field the Blueprint requires", () => {
    for (const f of ${JSON.stringify(bp.capabilityPolicy.bindings)}) {
      expect(CAPABILITY_BINDINGS).toContain(f);
    }
  });

  it("has a short TTL", () => {
    expect(CAPABILITY_TTL_SECONDS).toBeLessThanOrEqual(300);
    expect(CAPABILITY_TTL_SECONDS).toBeGreaterThan(0);
  });
});

describe("DENY is terminal", () => {
  it("cannot be rescued by a human approval", () => {
    expect(mayProceed("DENY", true)).toBe(false);
    expect(mayProceed("DENY", false)).toBe(false);
  });

  it("ESCALATE needs approval; ALLOW does not", () => {
    expect(requiresHumanApproval("ESCALATE")).toBe(true);
    expect(mayProceed("ESCALATE", false)).toBe(false);
    expect(mayProceed("ESCALATE", true)).toBe(true);
    expect(mayProceed("ALLOW", false)).toBe(true);
  });
});

describe("recipient policy", () => {
  it("refuses to pay an attacker address for a self-only action", () => {
    expect(() =>
      assertRecipientAllowed({ kind: SUPPORTED_ACTIONS[0]!, amount: 1n, recipient: ATTACKER }, SELF),
    ).toThrow(/RecipientNotAllowed/);
  });

  it("permits the position owner", () => {
    expect(() =>
      assertRecipientAllowed({ kind: SUPPORTED_ACTIONS[0]!, amount: 1n, recipient: SELF }, SELF),
    ).not.toThrow();
  });
});

describe("forbidden actions are not representable", () => {
  it("does not expose any action the Blueprint denied", () => {
    for (const forbidden of ["AAVE_WITHDRAW", "TRANSFER", "APPROVE_UNLIMITED"]) {
      expect(SUPPORTED_ACTIONS as readonly string[]).not.toContain(forbidden);
    }
  });
});
`,
    },
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: `contextlock-agent-${bp.identity.agentId}`,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: { typecheck: "tsc -p tsconfig.json --noEmit", test: "vitest run" },
          // Resolved from the pre-provisioned sandbox image; no install runs inside the sandbox.
          dependencies: { viem: "2.56.3", zod: "4.1.12" },
          devDependencies: { typescript: "5.9.3", vitest: "3.2.7" },
        },
        null,
        2,
      ),
    },
    {
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "NodeNext",
            moduleResolution: "NodeNext",
            strict: true,
            noUncheckedIndexedAccess: true,
            skipLibCheck: true,
            noEmit: true,
            types: [],
          },
          include: ["src/**/*.ts", "test/**/*.ts", "workflows/**/*.ts"],
        },
        null,
        2,
      ),
    },
    {
      path: ".env.example",
      content: `# ContextLock generated agent — variable NAMES only. Never put real values here.
#
# Your credentials stay yours. This project never asks for a CRE password, a 2FA code, a Ledger PIN
# or a seed phrase, and no generated file should ever contain one.

SEPOLIA_RPC_URL=
AGENT_ENS_NAME=${bp.identity.ensName}
CONTEXTLOCK_BROKER_URL=http://localhost:8787

# Authenticate the CRE CLI locally with \`cre login\`. Do not paste credentials anywhere else.
# Ledger: connect the device and use the supported device flow. WALLET_PASS stays in your shell.
`,
    },
    {
      path: "README.md",
      content: `# ${bp.identity.agentId}

${bp.objective}

Generated by ContextLock Studio from Blueprint \`${bp.blueprintId}\` revision ${bp.revision}.

## What this agent may do

${bp.permissions.allowed.map((p) => `- ${p.statement}`).join("\n")}

## What it may never do

${bp.permissions.denied.map((p) => `- ${p.statement}`).join("\n")}

## Authority model

The agent holds **no key**. It proposes an intent; a capability authorizing exactly one transaction
is issued only if live ENS identity, the confidential policy verdict, the nonce and the expiry all
hold. The executor re-checks every one of them on-chain.

- Autonomous, no human involved: ALLOW
- Held until a human approves the specific transaction: ESCALATE
- Refused, with no path to execution: DENY

DENY is structurally terminal. A human approval cannot turn it into an ALLOW.

## Honest status

- **Chainlink CRE**: \`${bp.cre.mode}\`. Not a live DON deployment, and nothing runs in a real TEE.
- **Ledger**: escalation mechanism is \`${bp.escalationPolicy.mechanism}\`. **No physical device
  evidence exists**${bp.ledger.blockerRef ? ` (${bp.ledger.blockerRef})` : ""}.
- Sepolia testnet only. Not audited.

## Run

\`\`\`bash
npm run typecheck
npm run test
\`\`\`

## Deploy

See \`DEPLOYMENT.md\`. Copy \`.env.example\` to \`.env\` and fill it in locally.
`,
    },
    {
      path: "DEPLOYMENT.md",
      content: `# Deployment

Sepolia testnet only. Every script asserts \`chainId == 11155111\`.

## 1. Credentials stay local

This project never collects your credentials, and neither did the Studio that generated it.

- **Chainlink CRE**: authenticate locally with \`cre login\`. Do not enter a CRE password or 2FA
  code into any web UI that is not Chainlink's own.
- **Ledger**: connect the device and use the supported device flow. Never type a seed phrase or PIN
  into software. \`WALLET_PASS\` stays in your shell and is never committed.
- **RPC and API keys**: \`.env\` only, which is gitignored.

## 2. Configure

\`\`\`bash
cp .env.example .env
\`\`\`

Resolve the values the Blueprint marked as unknown at design time:

${bp.protocols.flatMap((p) => p.contracts.filter((c) => !c.address.known).map((c) => `- \`${p.id}.${c.role}\` — ${(c.address as { reason: string }).reason}`)).join("\n") || "- none"}

## 3. Verify before funding

\`\`\`bash
npm run typecheck && npm run test
\`\`\`

Do not fund an agent whose tests do not pass. The tests are what demonstrate the boundaries this
agent claims to have.

## 4. Known limitations

- Not audited.
- ${bp.cre.mode === "official-cli-simulator" ? "The confidential policy has only been exercised in the CRE CLI simulator." : "Review the CRE deployment mode before relying on it."}
- No physical Ledger evidence${bp.ledger.blockerRef ? ` — ${bp.ledger.blockerRef}` : ""}.
`,
    },
  ],
};
