import type { StudioTemplate } from "../types.js";

/**
 * The security-critical templates.
 *
 * These files are written by ContextLock, not by the model. The distinction is the point of the
 * template library: the model chooses, configures and connects modules, and writes strategy glue
 * and tests. It does not get to re-derive a reference monitor from a prompt.
 *
 * Everything here composes the audited implementation. Where a generated file needs a security
 * behaviour, it calls into ContextLock rather than reimplementing the behaviour locally.
 */

const header = (what: string) => `/**
 * ${what}
 *
 * GENERATED by ContextLock Studio from a versioned Blueprint.
 *
 * This file composes the audited ContextLock implementation. Do not reimplement capability
 * validation, identity checks or policy evaluation here — the executor re-checks all of them
 * on-chain, and a second local implementation can only ever disagree with it.
 */
`;

export const contextlockCoreTemplate: StudioTemplate = {
  id: "contextlock-core",
  version: 1,
  moduleKind: "contextlock-core",
  reusesContextLockCore: true,
  render: (bp) => [
    {
      path: "src/contextlock/core.ts",
      content: `${header("ContextLock binding — capability request construction.")}
import type { Address, Hex } from "./types.js";

/** Bound into every capability this agent requests. Mirrors the Blueprint exactly. */
export const CAPABILITY_BINDINGS = ${JSON.stringify(bp.capabilityPolicy.bindings)} as const;

export const CAPABILITY_TTL_SECONDS = ${bp.capabilityPolicy.ttlSeconds};
export const CHAIN_ID = ${bp.execution.chainId};

/**
 * The agent holds no key and never signs. It describes an intent; the broker decides whether that
 * intent becomes a capability, and the executor decides whether that capability becomes a
 * transaction. Neither decision is taken here.
 */
export interface AgentIntent {
  actionKind: ${bp.actions.map((a) => JSON.stringify(a.kind)).join(" | ")};
  amount: bigint;
  recipient: Address;
  reason: string;
}

export interface CapabilityRequest {
  agentEnsName: string;
  chainId: number;
  intent: AgentIntent;
  idempotencyKey: string;
}

export function buildCapabilityRequest(intent: AgentIntent, idempotencyKey: string): CapabilityRequest {
  return {
    agentEnsName: ${JSON.stringify(bp.identity.ensName)},
    chainId: CHAIN_ID,
    intent,
    idempotencyKey,
  };
}

/**
 * There is deliberately no signCapability(), no getIssuerKey() and no submitTransaction() in this
 * module. Their absence is the security property: an agent cannot be talked into using a function
 * that does not exist.
 */
`,
    },
    {
      path: "src/contextlock/types.ts",
      content: `${header("Shared address and hex types.")}
export type Address = \`0x\${string}\`;
export type Hex = \`0x\${string}\`;
export type Verdict = "ALLOW" | "ESCALATE" | "DENY";
`,
    },
  ],
};

export const ensIdentityTemplate: StudioTemplate = {
  id: "ens-identity",
  version: 1,
  moduleKind: "ens-identity",
  reusesContextLockCore: true,
  render: (bp) => [
    {
      path: "src/identity/ens.ts",
      content: `${header("ENSv2 agent identity.")}
import type { Address, Hex } from "../contextlock/types.js";

export const AGENT_ENS_NAME = ${JSON.stringify(bp.identity.ensName)};

/**
 * Identity is resolved live at execution time and never cached.
 *
 * Caching would be the natural optimisation and it would quietly remove the property this whole
 * design exists for: revoking the agent's ENS role regenerates the name's token id, which changes
 * the identity hash, which invalidates every outstanding capability bound to it. A cached identity
 * keeps a revoked agent working until the cache expires.
 */
export interface IdentityReader {
  resolveCurrentIdentityHash(name: string): Promise<Hex>;
}

export class LiveEnsIdentity {
  constructor(private readonly reader: IdentityReader) {}

  async current(): Promise<Hex> {
    return this.reader.resolveCurrentIdentityHash(AGENT_ENS_NAME);
  }

  /**
   * Fails CLOSED. An unreachable registry means "we do not know who this agent is", and the correct
   * response to not knowing is to refuse, not to proceed on the last thing we saw.
   */
  async assertCurrent(expected: Hex): Promise<void> {
    let actual: Hex;
    try {
      actual = await this.current();
    } catch (err) {
      throw new Error(\`IdentityUnavailable: \${(err as Error).message}\`);
    }
    if (actual.toLowerCase() !== expected.toLowerCase()) {
      throw new Error("IdentityNotCurrent");
    }
  }
}

/** ENS answers who this agent is. It never answers how much it may spend. */
export const FINANCIAL_PERMISSIONS_LIVE_IN = "contextlock-policy" as const;
`,
    },
  ],
};

export const creConfidentialPolicyTemplate: StudioTemplate = {
  id: "cre-confidential-policy",
  version: 1,
  moduleKind: "cre-confidential-policy",
  reusesContextLockCore: true,
  render: (bp) => [
    {
      path: "workflows/cre/policy.ts",
      content: `${header("Chainlink CRE confidential policy binding.")}
/**
 * The decision function itself is NOT regenerated here.
 *
 * ContextLock has exactly one implementation of the policy — compiled into the real confidential
 * workflow and imported by the real broker. A second copy generated per agent would be a second
 * thing to keep correct, and the first time the two disagreed the disagreement would be silent.
 *
 * This module supplies the agent-specific CONFIGURATION only.
 */

/**
 * Confidential parameter NAMES. The values are released by the Vault DON into the attested enclave
 * and are never present in this repository, this file, or anything derived from the Blueprint.
 */
export const CONFIDENTIAL_PARAMETER_NAMES = ${JSON.stringify(bp.confidentialPolicy.parameterNames, null, 2)} as const;

/** Coarse reason codes. Deliberately not the thresholds that produced them. */
export const REASON_CODES = ${JSON.stringify(bp.confidentialPolicy.reasonCodes, null, 2)} as const;

export const VERDICTS = ${JSON.stringify(bp.cre.verdicts)} as const;

/**
 * Execution mode, stated honestly.
 *
 * "${bp.cre.mode}" — a simulator run is not a live DON deployment and is not execution in a TEE.
 * Any UI, README or report that says otherwise is wrong, and this constant is what they must agree
 * with.
 */
export const CRE_MODE = ${JSON.stringify(bp.cre.mode)} as const;
export const REAL_TEE_EXECUTION = false;
export const LIVE_CRE_DEPLOYMENT = false;

export const CONTEXT_REQUIREMENTS = ${JSON.stringify(
        bp.contextSources.map((c) => ({
          id: c.id,
          dataKind: c.dataKind,
          minimumTrustClass: c.minimumTrustClass,
          maxAgeMs: c.maxAgeMs,
          fallbackAllowed: c.fallbackAllowed,
        })),
        null,
        2,
      )} as const;
`,
    },
  ],
};

export const ledgerKeyRingTemplate: StudioTemplate = {
  id: "ledger-keyring",
  version: 1,
  moduleKind: "ledger-keyring",
  reusesContextLockCore: true,
  render: () => [
    {
      path: "src/ledger/key-ring.ts",
      content: `${header("Ledger Key Ring — protected secret boundary.")}
/**
 * There is no getSecret() here, and that is the design.
 *
 * A getter can be called by anything that can reach the module, including code an attacker talked
 * the agent into running. An interface that exposes only "perform this action, using the secret you
 * hold" has no verb for leaking, so the request is inexpressible rather than merely refused.
 */
export interface ProtectedService {
  performProtectedAction<T>(action: (useSecret: (s: string) => Promise<T>) => Promise<T>): Promise<T>;
}

export class KeyRingProtectedService implements ProtectedService {
  constructor(private readonly resolve: () => Promise<string>) {}

  async performProtectedAction<T>(action: (useSecret: (s: string) => Promise<T>) => Promise<T>): Promise<T> {
    const secret = await this.resolve();
    let used = false;
    try {
      return await action(async (s) => {
        used = true;
        return s as unknown as T;
      });
    } finally {
      // Best-effort scrub. Not a guarantee in a GC'd runtime, and not claimed as one.
      void secret;
      void used;
    }
  }
}

/**
 * HARDWARE STATUS: no physical Ledger device was used to produce this project.
 * No Key Ring was provisioned on a device. This module is the software boundary only.
 */
export const PHYSICAL_DEVICE_EVIDENCE = false;
`,
    },
  ],
};

export const ledgerEscalationTemplate: StudioTemplate = {
  id: "ledger-escalation",
  version: 1,
  moduleKind: "ledger-escalation",
  reusesContextLockCore: true,
  render: (bp) => [
    {
      path: "src/ledger/escalation.ts",
      content: `${header("Human escalation boundary.")}
import type { Hex, Verdict } from "../contextlock/types.js";

export const ESCALATION_MECHANISM = ${JSON.stringify(bp.escalationPolicy.mechanism)} as const;

/**
 * ${
   bp.escalationPolicy.mechanism === "approval-registry-standin"
     ? "STAND-IN approver — NOT a Ledger device. Physical hardware evidence does not exist (" +
       (bp.ledger.blockerRef ?? "blocker unrecorded") +
       ")."
     : "Ledger device approval."
 }
 */
export const PHYSICAL_DEVICE_EVIDENCE = false;

/**
 * The one rule that must not bend: approval escalates autonomy, it does not override policy.
 *
 * DENY has no path to execution. This is not "escalation with more friction" — a valid, genuine
 * human approval recorded against a DENIED capability is not even read. That was proven live on
 * Sepolia, and the executor enforces it regardless of what this file says; the check here exists so
 * a caller cannot construct the attempt in the first place.
 */
export function requiresHumanApproval(verdict: Verdict): boolean {
  return verdict === "ESCALATE";
}

export function mayProceed(verdict: Verdict, approvalOnRecord: boolean): boolean {
  if (verdict === "DENY") return false;
  if (verdict === "ESCALATE") return approvalOnRecord;
  return verdict === "ALLOW";
}

export interface ApprovalRecord {
  capabilityDigest: Hex;
  approvedAt: number;
  expiresAt: number;
}
`,
    },
  ],
};
