/**
 * Writes move/kido_nautilus/tests/vectors.move: decisions signed by the TypeScript enclave signer
 * with a fixed test seed, so the Move verifier is tested against exactly what Kido produces.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { keccak256, toHex, type Hex } from "viem";
import { LocalEnclaveSigner, type SignedDecision } from "../src/nautilus.js";

const T0 = 1_800_000_000_000n; // ms
const signer = LocalEnclaveSigner.fromSeed(new Uint8Array(32).fill(0x2a));
const other = LocalEnclaveSigner.fromSeed(new Uint8Array(32).fill(0x2b));
const key = keccak256(toHex("kido.decision.hf-threshold"));
const bp = keccak256(toHex("blueprint r3"));
const cases: [string, SignedDecision][] = [
  ["act_at_t0", await signer.sign({ decisionKey: key, act: true, blueprintHash: bp, timestampMs: T0 })],
  ["hold_at_t1", await signer.sign({ decisionKey: key, act: false, blueprintHash: bp, timestampMs: T0 + 60_000n })],
  ["act_at_t0_other_key", await other.sign({ decisionKey: key, act: true, blueprintHash: bp, timestampMs: T0 })],
];
const hexv = (h: Hex) => `x"${h.slice(2)}"`;
const fns = cases.map(([n, d]) => `public fun ${n}(): Signed { Signed { decision_key: ${hexv(d.decisionKey)}, act: ${d.act}, blueprint_hash: ${hexv(d.blueprintHash)}, timestamp_ms: ${d.timestampMs}, signature: ${hexv(d.signature)} } }`);
const move = `// Generated by packages/privacy/scripts/nautilus-vectors.ts. Do not edit.
#[test_only]
module kido_nautilus::vectors;

public struct Signed has copy, drop { decision_key: vector<u8>, act: bool, blueprint_hash: vector<u8>, timestamp_ms: u64, signature: vector<u8> }

public fun fields(s: &Signed): (vector<u8>, bool, vector<u8>, u64, vector<u8>) { (s.decision_key, s.act, s.blueprint_hash, s.timestamp_ms, s.signature) }
public fun t0_ms(): u64 { ${T0} }
public fun enclave_pk(): vector<u8> { ${hexv(signer.publicKey)} }

${fns.join("\n")}
`;
writeFileSync(resolve(import.meta.dirname, "../../../move/kido_nautilus/tests/vectors.move"), move);
console.log(`wrote ${cases.length} signed decision vectors`);
