import type { ContextLockAgentBlueprint } from "@contextlock/studio-blueprint";
import type { TemplateFile } from "../types.js";

/**
 * Generic adapter code generation.
 *
 * There is no per-provider branch here and there must never be one. An adapter contributes its own
 * files through its manifest and its `generateTemplateConfig()`; this function renders whatever the
 * Blueprint's bindings describe. Adding Uniswap, The Graph or Chainlink in a later phase adds a
 * manifest to the registry — not a case to this switch, because there is no switch.
 *
 * What IS shared, and belongs here rather than in each adapter, is the boundary every adapter's
 * generated code has to respect:
 *
 *  - a data adapter's output enters policy only as a provenanced observation;
 *  - an execution adapter's output is decoded and re-validated before anything signs it;
 *  - neither one ever holds a credential in the generated agent.
 */

export interface AdapterRenderContext {
  adapterId: string;
  adapterVersion: string;
  role: string;
  configRef: string;
  /** From the adapter's own generateTemplateConfig(). Opaque to this renderer. */
  config: Record<string, unknown>;
  requirement?: {
    kind: string;
    minimumTrustClass: string;
    maxAgeMs: number;
    unit?: string | undefined;
    confidential: boolean;
    fallback?: { adapterId: string; adapterVersion: string; allowedTrust: string; maxAgeMs: number } | undefined;
  };
}

const header = (title: string) => `/**
 * ${title}
 *
 * GENERATED by ContextLock Studio from a versioned Blueprint. Do not edit by hand: the Blueprint is
 * the source of truth, and a change here would be silently reverted by the next build.
 */
`;

/** Shared runtime the generated adapters compose. Written once, not per provider. */
export function renderAdapterKernel(): TemplateFile[] {
  return [
    {
      path: "src/adapters/kernel.ts",
      content: `${header("Adapter kernel — the boundary every generated adapter respects.")}
export type DataTrustClass =
  | "CONFIDENTIAL_VERIFIED_COMPUTE"
  | "VERIFIED_ORACLE"
  | "INDEXED_CHAIN_DATA"
  | "DIRECT_CHAIN_DATA"
  | "EXTERNAL_API"
  | "USER_UNTRUSTED";

const RANK: Record<DataTrustClass, number> = {
  CONFIDENTIAL_VERIFIED_COMPUTE: 5,
  VERIFIED_ORACLE: 4,
  INDEXED_CHAIN_DATA: 3,
  DIRECT_CHAIN_DATA: 2,
  EXTERNAL_API: 1,
  USER_UNTRUSTED: 0,
};

export function satisfiesTrust(offered: DataTrustClass, required: DataTrustClass): boolean {
  return RANK[offered] >= RANK[required];
}

export interface Provenance {
  provider: string;
  adapterId: string;
  adapterVersion: string;
  trustClass: DataTrustClass;
  sourceTimestamp?: string;
  freshnessMs?: number;
  chainId?: number;
  blockNumber?: string;
  indexedBlock?: string;
  chainHeadBlock?: string;
  blockLag?: number;
  feedId?: string;
  subgraphId?: string;
  verification: { verified: boolean; mechanism?: string };
}

export interface DataObservation {
  observationId: string;
  dataKind: string;
  subject?: string;
  /** Integer base units as a string. A price is not a JS number. */
  value: string;
  unit: string;
  decimals: number;
  observedAt: string;
  provenance: Provenance;
}

export class TrustRequirementError extends Error {
  constructor(offered: DataTrustClass, required: DataTrustClass, kind: string) {
    super(\`"\${kind}" requires \${required} but the value is \${offered}\`);
    this.name = "TrustRequirementError";
  }
}

export class FreshnessRequirementError extends Error {
  constructor(ageMs: number | undefined, maxAgeMs: number, kind: string) {
    super(
      ageMs === undefined
        ? \`"\${kind}" carries no freshness information and cannot satisfy maxAgeMs=\${maxAgeMs}\`
        : \`"\${kind}" is \${ageMs}ms old, limit is \${maxAgeMs}ms\`,
    );
    this.name = "FreshnessRequirementError";
  }
}

/**
 * The gate every observation passes before it can influence a decision.
 *
 * Fails closed on missing freshness. "We do not know how old this is" is not "it is fine" — that
 * substitution is how a stale price authorizes a trade.
 */
export function requireObservation(
  obs: DataObservation,
  req: { kind: string; minimumTrustClass: DataTrustClass; maxAgeMs: number },
): DataObservation {
  if (!satisfiesTrust(obs.provenance.trustClass, req.minimumTrustClass)) {
    throw new TrustRequirementError(obs.provenance.trustClass, req.minimumTrustClass, req.kind);
  }
  const age = obs.provenance.freshnessMs;
  if (age === undefined || age > req.maxAgeMs) {
    throw new FreshnessRequirementError(age, req.maxAgeMs, req.kind);
  }
  return obs;
}

/** A provider-built transaction, re-derived from its own calldata. Never from a provider summary. */
export interface NormalizedAction {
  chainId: number;
  target: string;
  calldata: string;
  value: string;
  actionType: string;
  recipient?: string;
  spender?: string;
  allowanceChanges: Array<{ token: string; spender: string; amount: string; unlimited: boolean }>;
  minOutputs: Array<{ token: string; amount: string }>;
  deadline?: string;
}

export class ExecutionValidationError extends Error {
  constructor(readonly code: string, detail: string) {
    super(\`\${code}: \${detail}\`);
    this.name = "ExecutionValidationError";
  }
}
`,
    },
  ];
}

/** Render one bound adapter. Provider-agnostic by construction. */
export function renderAdapter(ctx: AdapterRenderContext): TemplateFile[] {
  const dir = `src/adapters/${ctx.adapterId}`;
  const isExecution = ctx.role === "EXECUTION";

  const files: TemplateFile[] = [
    {
      path: `${dir}/config.ts`,
      content: `${header(`${ctx.adapterId} — pinned configuration.`)}
/**
 * The adapter version is PINNED. Registering a newer adapter upstream does not change what this
 * build runs: every simulation result recorded against this project was produced with this exact
 * version, and swapping it would invalidate that evidence with nothing saying so.
 */
export const ADAPTER_ID = ${JSON.stringify(ctx.adapterId)} as const;
export const ADAPTER_VERSION = ${JSON.stringify(ctx.adapterVersion)} as const;
export const ADAPTER_ROLE = ${JSON.stringify(ctx.role)} as const;
export const SERVES = ${JSON.stringify(ctx.configRef)} as const;

export const ADAPTER_CONFIG = ${JSON.stringify(ctx.config, null, 2)} as const;
${
  ctx.requirement
    ? `
/** The requirement this adapter was selected to satisfy, enforced at every read. */
export const REQUIREMENT = {
  kind: ${JSON.stringify(ctx.requirement.kind)},
  minimumTrustClass: ${JSON.stringify(ctx.requirement.minimumTrustClass)},
  maxAgeMs: ${ctx.requirement.maxAgeMs},
  unit: ${JSON.stringify(ctx.requirement.unit ?? null)},
  confidential: ${ctx.requirement.confidential},
} as const;

/**
 * ${
   ctx.requirement.fallback
     ? `Declared fallback: ${ctx.requirement.fallback.adapterId}@${ctx.requirement.fallback.adapterVersion}, ` +
       `at most ${ctx.requirement.fallback.allowedTrust} within ${ctx.requirement.fallback.maxAgeMs}ms.`
     : "No fallback is declared. If this source is unavailable the decision fails closed rather than silently using a weaker one."
 }
 */
export const FALLBACK${ctx.requirement.fallback ? "" : ": null"} = ${
      ctx.requirement.fallback ? `${JSON.stringify(ctx.requirement.fallback, null, 2)} as const` : "null"
    };
`
    : ""
}`,
    },
  ];

  if (isExecution) {
    files.push({
      path: `${dir}/adapter.ts`,
      content: `${header(`${ctx.adapterId} — execution adapter binding.`)}
import { ExecutionValidationError, type NormalizedAction } from "../kernel.js";
import { ADAPTER_ID, ADAPTER_VERSION } from "./config.js";

/**
 * What the provider builds is a PROPOSAL, not an authorization.
 *
 * The provider is a third party. It may be compromised, it may be buggy, and its own description of
 * what it built is not evidence — a provider that wanted to mislead would return a benign summary
 * beside hostile calldata. So the calldata is decoded independently and compared to the intent
 * before anything signs it, and ContextLock re-checks the result on-chain regardless.
 */
export interface ExecutionConstraints {
  chainId: number;
  allowedTargets: readonly string[];
  allowedRecipients: readonly string[] | "self-only";
  owner: string;
  allowUnlimitedApprovals: boolean;
  maxQuoteAgeMs: number;
}

export function assertMatchesIntent(
  normalized: NormalizedAction,
  intent: { recipient: string; amount: string },
  c: ExecutionConstraints,
): void {
  if (normalized.chainId !== c.chainId) {
    throw new ExecutionValidationError("CHAIN_MISMATCH", \`decoded chain \${normalized.chainId} != \${c.chainId}\`);
  }
  if (!c.allowedTargets.map((t) => t.toLowerCase()).includes(normalized.target.toLowerCase())) {
    throw new ExecutionValidationError("TARGET_NOT_ALLOWED", \`decoded target \${normalized.target}\`);
  }
  const decoded = (normalized.recipient ?? "").toLowerCase();
  if (decoded !== intent.recipient.toLowerCase()) {
    throw new ExecutionValidationError("RECIPIENT_MISMATCH", \`decoded \${decoded}, intended \${intent.recipient}\`);
  }
  if (c.allowedRecipients === "self-only") {
    if (decoded !== c.owner.toLowerCase()) {
      throw new ExecutionValidationError("RECIPIENT_NOT_SELF", \`policy is self-only, decoded \${decoded}\`);
    }
  } else if (!c.allowedRecipients.map((r) => r.toLowerCase()).includes(decoded)) {
    throw new ExecutionValidationError("RECIPIENT_NOT_ALLOWED", \`decoded \${decoded}\`);
  }
  for (const a of normalized.allowanceChanges) {
    if (a.unlimited && !c.allowUnlimitedApprovals) {
      throw new ExecutionValidationError("UNLIMITED_APPROVAL", \`spender \${a.spender}\`);
    }
  }
}

export const ADAPTER = { id: ADAPTER_ID, version: ADAPTER_VERSION } as const;
`,
    });
  } else {
    files.push({
      path: `${dir}/adapter.ts`,
      content: `${header(`${ctx.adapterId} — data adapter binding.`)}
import { requireObservation, type DataObservation } from "../kernel.js";
import { ADAPTER_ID, ADAPTER_VERSION${ctx.requirement ? ", REQUIREMENT" : ""} } from "./config.js";

/**
 * Data enters a decision only as a provenanced observation that meets its requirement.
 *
 * A bare number cannot be checked: "is this fresh enough" and "is this trusted enough" are both
 * unanswerable without knowing where it came from. That is why provenance is mandatory rather than
 * decorative, and why this read gate is not optional.
 */
export function read(observation: DataObservation): DataObservation {
${
  ctx.requirement
    ? `  return requireObservation(observation, REQUIREMENT);`
    : `  return observation;`
}
}

export const ADAPTER = { id: ADAPTER_ID, version: ADAPTER_VERSION } as const;
`,
    });
  }

  return files;
}
